spring.application.name=auth-service
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/flexsim-database
spring.datasource.username=postgres
spring.datasource.password=${POSTGRES_PASSWORD}

spring.flyway.enabled=true
spring.flyway.schemas=auth
spring.flyway.locations=classpath:db/migration

spring.jpa.properties.hibernate.default_schema=auth
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false


spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000

jwt.secret=${JWT_SECRET}
jwt.expiration-ms=86400000

