apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-service
  namespace: flexsim
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-service
  template:
    metadata:
      labels:
        app: file-service
    spec:
      containers:
        - name: file-service
          image: project_for_interview-file-service
          imagePullPolicy: Never
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/flexsim_database
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: file-service
  namespace: flexsim
spec:
  selector:
    app: file-service
  ports:
    - port: 8083
      targetPort: 8083