apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: flexsim
type: Opaque
stringData:
  POSTGRES_PASSWORD: Neelam@3008
  JWT_SECRET: NeelamFlexsimJwtSecretKeyForLocalDevelopment2026@Secure123