spring.application.name=simulation-service
server.port = 8084
spring.datasource.url=jdbc:postgresql://localhost:5432/flexsim-database
spring.datasource.username=postgres
spring.datasource.password=${POSTGRES_PASSWORD}


spring.flyway.enabled=true
spring.flyway.schemas=simulation
spring.flyway.locations=classpath:db/migration



spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000

spring.jpa.properties.hibernate.default_schema=simulation
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

jwt.secret=${JWT_SECRET}

# dummy = fake FlexSim (this phase). real = your original ProcessBuilder + flexsim.exe (later)
flexsim.mode=dummy
flexsim.path=C:/Program Files/FlexSim 2025/program/flexsim.exe
flexsim.callback-host=localhost
flexsim.callback-port=8084
flexsim.dummy-stage-delay-ms=45000

# spring.kafka.bootstrap-servers=localhost:9092
# spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
# spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# simulation.max-concurrent-runs=4

spring.config.import=classpath:kafka.yml